### ISSUE TITLE
alpha must satisfy: 0 < alpha <= 1

### ISSUE THREAD

**Issue by anilbhatt** [arkochhar/Technical-Indicators#4]
Hi 

When i'm trying to run unit test cases getting this error.

EMA Test with alpha False
Time taken by Pandas computations for EMA 0.00962901115417
Time taken by manual computations for EMA 0.0966241359711
        Total Rows: 5232
        Columns Match: 5
        Success Rate: 0.0%
EMA Test with alpha True
Traceback (most recent call last):
  File "indicator.py", line 763, in <module>
    test_EMA(df, forATR=True)
  File "indicator.py", line 388, in test_EMA
    EMA(df, colFrom, colTo, test_period, alpha=forATR)
  File "indicator.py", line 142, in EMA
    df[target] = con.ewm(alpha=1 / period, adjust=False).mean()
  File "/Users/anil.bhatt/anaconda/lib/python2.7/site-packages/pandas/core/generic.py", line 6069, in ewm
    adjust=adjust, ignore_na=ignore_na, axis=axis)
  File "/Users/anil.bhatt/anaconda/lib/python2.7/site-packages/pandas/core/window.py", line 2066, in ewm
    return EWM(obj, **kwds)
  File "/Users/anil.bhatt/anaconda/lib/python2.7/site-packages/pandas/core/window.py", line 1658, in __init__
    self.com = _get_center_of_mass(com, span, halflife, alpha)
  File "/Users/anil.bhatt/anaconda/lib/python2.7/site-packages/pandas/core/window.py", line 1971, in _get_center_of_mass
    raise ValueError("alpha must satisfy: 0 < alpha <= 1")
ValueError: alpha must satisfy: 0 < alpha <= 1

Can you please help here

**Comment by alchem9st** [comment]
Try with python3, it should resolve your error.
This was due to the fact how division('/') is handled differently in py2.x and py3.x.
:D

**Comment by arkochhar** [comment]
This code has been developed and test for python3 only. Please refer to comment by @alchem9st. Closing the issue.
